name: CI
on: [push, pull_request]

permissions:
  contents: read #  to fetch code (actions/checkout)

jobs:
    tests:
        name: Tests
        timeout-minutes: 10
        runs-on: ${{ matrix.os }}
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-version }}
            -   name: Composer Install
                run: composer install --no-interaction --no-cache
            -   name: PHPUnit
                run: vendor/bin/phpunit
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                php-version: ['8.1', '8.2', '8.3']
